config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  get 'posts/index'

  get 'home/top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resource :posts,          only: [:create, :destroy]
  
  root "posts#index"
  
  get "posts/new" => "posts#new"
  
  post "posts/create" => "posts#create"
  
  get "posts/:id/edit" => "posts#edit"
  
  post "posts/:id/update" => "posts#update"
  
  post "posts/:id/destroy" => "posts#destroy"
  
  get 'posts/:id' => 'posts#show'
  
  get  '/signup',  to: 'users#new'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  resources :relationships,       only: [:create, :destroy]
  
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HimaBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
  <div class="header-logo">
    <%= link_to("HimaBoard","/posts/index") %>
  </div>
  <ul class="header-menus">
    <li>
      
      <%= link_to("新規投稿","/posts/new",class: "btn btn-lg btn-primary") %>
      <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path,class: "btn btn-lg btn-primary" %></li>
        <% end %>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    </li>
  </ul>
</header>

<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
<% end %>


    

    <%= yield %>
    
    <%= debug(params) if !Rails.env.development? %>
    
    
  </body>
</html>